version: "3.8"

services:
  mongodb:
    container_name: mongo
    volumes:
      - ./backend/data:/data
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  fronend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"

volumes:
  data:
