name: wanderlust_1

on: 
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Container Remove
        run: sudo docker-compose down
        
      - name: Debug - list files
        run: ls -la ./backend/data

      - name: Build and run docker-compose
        run: sudo docker-compose -f docker-compose.yml up -d --build

      - name: Copy mongo data json to container
        run: sudo docker cp ./backend/data/sample_posts.json mongo:/data/sample_posts.json

      - name: Import data into Mongo container
        run: sudo docker exec mongo mongoimport --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray

               

        
