name: wanderlust_1

on: 
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - list files
        run: ls -la ./backend/data

      - name: Install Docker Compose
      - run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and run docker-compose
        run: sudo docker-compose -f docker-compose.yml up -d --build

      - name: Copy mongo data json to container
        run: sudo docker cp ./backend/data/sample_posts.json mongo:/tmp/sample_posts.json/sample_posts.json

      - name: Import data into Mongo container
        run: sudo docker exec mongo mongoimport --db wanderlust --collection posts --file /tmp/sample_posts.json/sample_posts.json --jsonArray

               

        
