name: Git repo clone

on: 
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
        - name: hello
          run: sudo apt update -y
  
        - name: nginx install on ubuntu
          run: sudo apt install nginx -y
        
